(feat) O3-4068 Add ability to preview clinical view configurations in…
openmrs/openmrs-esm-clinical-views-builder pull request #10
Opened 2024-10-09 11:56 UTC by CynthiaKamau

… the patient chart

## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Summary

Add ability to preview clinical view configurations in the patient chart

## Screenshots

https://github.com/user-attachments/assets/bcc332c5-e8f2-48ef-ac9c-6d4cb10bb18d

## Related Issue

## Other

2024-10-11 07:53 UTC, lucyjemutai commented
Thanks @CynthiaKamau ]

Looks Good.

Were these translation changes manually committed, or were they automatically added by Git?

2024-10-11 08:02 UTC, lucyjemutai approved these changes

2024-10-11 08:05 UTC, CynthiaKamau commented
> Thanks @CynthiaKamau ]
> 
> Looks Good.
> 
> Were these translation changes manually committed, or were they automatically added by Git?

They are added when i do commits

2024-10-11 11:23 UTC, eudson requested changes
Check the suggested changes for the `renderingError` and apply everywhere

2024-10-11 11:23 UTC, eudson commented on src/components/view-editor/view-editor.component.tsx
> +        title: t('errorRendering', 'Error rendering'),
```suggestion
        title: t('renderingError', 'Rendering Error'),
```

2024-10-11 11:23 UTC, eudson commented on src/components/view-editor/view-editor.component.tsx
> +        localStorage.setItem(schemaId, JSON.stringify(schema));
I would suggest you create a small function called updateSchema, you can use here and on line 174 and remove the comment on the line above. This is just for readability purposes, otherwise just remove the comment

2024-10-11 11:23 UTC, eudson commented on src/components/view-editor/view-editor.component.tsx
> +  const handlePreviewPackage = () => {
```suggestion
  const handlePreviewClinicalView= () => {
```

2024-10-11 11:23 UTC, eudson commented on src/components/view-editor/view-editor.component.tsx
> +    window.open(window.getOpenmrsSpaBase() + `patient/${patientUuid}/chart/Patient%20Summary`);
why not opening the entry point of the Clinical View?

2024-10-11 11:23 UTC, eudson commented on src/config-schema.ts
> +    _description: 'UUID for the stock item category',
Stock item?

2024-10-11 11:23 UTC, eudson commented on translations/am.json
> +  "errorRendering": "Error rendering",
```suggestion
  "renderingError": "Rendering Error",
```

2024-10-12 07:32 UTC, CynthiaKamau commented on src/components/view-editor/view-editor.component.tsx
> +    window.open(window.getOpenmrsSpaBase() + `patient/${patientUuid}/chart/Patient%20Summary`);
The preview is on the patient chart, because there is no way to view the chart side nav from the builder, on the form engine its easier because the libraries main component can be easily exposed

2024-10-14 15:53 UTC, eudson approved these changes
LGTM

2024-10-14 15:53 UTC, merged